### ISSUE TITLE
Optimisation:

### ISSUE THREAD

**Issue by at67** [delpozzo/gigatron#1]
I haven't tried running your code yet, although I have been mighty tempted; I am waiting until you decide it is finished and then I will play the snot out of it.

One thing I noticed perusing your code is that there is a lot of array(array()) type accesses that are duplicated, not only are these types of array accesses somewhat slow compared to zero page accesses but they can lead to massive code bloat. Once you have validated the logic statements referencing those array accesses, I would personally alias them into zero page variables something like this, (this assumes you haven't already used the entire 40 zero page variables available to gtBASIC):
```
checkHand:
    .
    .
    .
' sort cards least to greatest
    gosub sortCards

    card0 = cardValue(hand(0))
    card1 = cardValue(hand(1))
    card2 = cardValue(hand(2))
    card3 = cardValue(hand(3))
    card4 = cardValue(hand(4))
    .
    .
    .
' modified card logic functions using aliased variables, do it for other applicable functions as well
twoPair:
    if (card0 = card1) AND (card2 = card3) 
        winType = TWOPAIR
    elseif (card1 = card2) AND (card3 = card4) 
        winType = TWOPAIR
    elseif (card0 = card1) AND (card3 = card4) 
        winType = TWOPAIR
    endif
return
    .
    .
    .
```
I didn't check your code in complete detail, but if you need to write the results of the aliased variables then you can do it at the end of the checkHand as the reverse of the aliased reads I inserted at the start of checkHand.

This will not only make a speed difference in your code, but even more importantly will make a substantial size difference to it's RAM usage as well; I wouldn't be surprised if you saved around 1KBytes or more of RAM doing this.

**Comment by delpozzo** [comment]
This is great advice at67, thank you!! I am nearly done with Video Poker, all that remains is adding some sound effects and that is really about it. Your ears must have been ringing, because the first thing I was going to ask you when I post this to the Gigatron forums is what optimizations I can make and if I made any glaring mistakes in gtBASIC :-P One thing I didn't quite understand is when to use **=** / **<** / **>** in a comparison vs **&=** / **&< /** **&>**. I ended up just using what worked without knowing why. Sometimes **=** works fine, other times I had to use **&=**.

**Comment by delpozzo** [comment]
(I finished adding sounds last night and just posted this to the Gigatron forums)

**Comment by at67** [comment]
The & symbol is used to control how branches and jumps are optimised. e.g.

1) No '&' symbol produces ordinary code that allows the full use of relational logic, (but produces the slowest and largest code).
~~~
if (a = 1) AND (b = 2)
    ...
endif
~~~

2) One '&' symbol removes the call to the runtime relational logic subroutines and uses jump macros that can jump between pages, (this produces faster and slightly smaller code at the expense of not allowing relational operators). So to implement the above if statement you would need to do something like this:
~~~
if &a = 1
    if &b = 2
        ...
    endif
endif
~~~

3) Two '&&' symbols does the same as one '&' symbol but goes even further and replaces the jump macros with inline branches for the most optimal production of code in terms of speed and size, (branches are limited to branching within the same page which can be quite limiting depending on the size of the page, e.g. offscreen video memory pages).
~~~
if &&a = 1
    if &&b = 2
        ...
    endif
endif
~~~

I use option 1 for general code readability and when debugging algorithms.

I use option 2 when beginning the optimisation phase, it can substantially increase code speed but more importantly reduce code size and thus allowing for more code to be added once you start hitting the Gigatron's RAM limits.

I use option 3 inside tight loops and when I have completely run out of Gigatron RAM, it's the most powerful of the user controllable optimisation hints, but produces code that is inherently page limited with branches. e.g. you optimise a subroutine using '&&' which may save you many tens of bytes, this now relocates all subsequent code at higher addresses by those tens of bytes. If any of the subsequent code at higher addresses also contains '&&' optimisations then it has a good chance of breaking as it produces code that tries to branch between pages, (the optimiser pass will warn you of these situations and not allow the code to compile or run).

I basically never use '&&' unless the code is in an inner tight loop or I have run out of RAM, PucMon extensively uses it throughout the entirety of it's code, without this hint PucMon would never have been possible with sound effects, (the '&&' hint saved around 3.5K of RAM for the entire project).

Note the '&' hint can be used on for next loops, repeat until loops, goto's and gosub's as well, basically code that can generate some kind of jump can be optimised into a branch using '&'.

The '&&' hint is only used for IF statements.

**Comment by delpozzo** [comment]
Thank you for taking the time to explain, this all makes A LOT of sense now. During early development, I was primarily using &=, &<, &> for comparisons. When the time came to make two comparisons (with an AND) it all fell apart. I will definitely keep this in mind when I begin optimizing. The current compiler output is below, I'm curious to see the before/after results:

```
****************************************************************************************************
* Assembling file '../../../delpozzo/VideoPoker/VideoPoker.gasm'
****************************************************************************************************

Output : ../../../delpozzo/VideoPoker/VideoPoker.gt1

**********************************************
*                   Loading                    
**********************************************
* ../../../delpozzo/VideoPoker/VideoPoker.gt1 : 0x0200  :  8430 bytes
**********************************************
* Free RAM after load  :    678
**********************************************
```

**Comment by at67** [comment]
Did you ever get a chance to optimise your code and compare the resultant difference in size/speed?

I'll be releasing a new version of the compiler and associated tools hopefully in the next 2 weeks and a quick heads up, you won't have to save your TGA images upside down anymore. I had already coded an XY flipping function in my TGA loader, (the TGA format allows for an arbitrary origin), but I had disabled it; no idea why, but it's enabled now and auto flipping images on load into the Gigatron's memory.

**Comment by delpozzo** [comment]
Unfortunately I've been quite busy the past couple of months, but I do plan on getting back to it this week now that things have settled down :-)

I am looking forward to the next version of your compiler! I must admit that I was curious as to why the TGA files had to be upside down, but it was no trouble to flip them in GIMP :-P

**Comment by delpozzo** [comment]
I just committed the optimizations and wow! More than double the RAM is now free, fantastic! Went from 678 to 1599. This also does appear to speed up the hand evaluations. There used to be a slight delay before the victory chime plays, but now it is pretty much instanteanous-- even for Jacks or Better which is the last hand to get evaluated.

**Before optimization:**

```
****************************************************************************************************
* Assembling file '../../../delpozzo/VideoPoker/VideoPoker.gasm'
****************************************************************************************************

Output : ../../../delpozzo/VideoPoker/VideoPoker.gt1

**********************************************
*                   Loading                    
**********************************************
* ../../../delpozzo/VideoPoker/VideoPoker.gt1 : 0x0200  :  8430 bytes
**********************************************
* Free RAM after load  :    678
**********************************************
```

**After:**
```
****************************************************************************************************
* Assembling file '../../../delpozzo/VideoPoker/VideoPoker.gasm'
****************************************************************************************************

Output : ../../../delpozzo/VideoPoker/VideoPoker.gt1

**********************************************
*                   Loading                    
**********************************************
* ../../../delpozzo/VideoPoker/VideoPoker.gt1 : 0x0200  :  8198 bytes
**********************************************
* Free RAM after load  :   1599
**********************************************
```

**Comment by at67** [comment]
Excellent, well done!
